-- =====================================================================
-- Seed data: roles_config, labour_rates, sites (116)
-- Idempotent (on conflict do nothing) so it can be re-run safely.
-- =====================================================================

insert into public.roles_config (tier, display_name) values
  (1, 'Plant Manager'),
  (2, 'Fabrication Engineer'),
  (3, 'Fabrication Manager')
on conflict (tier) do nothing;

insert into public.labour_rates (designation, rate_aed_per_hr) values
  ('Welder', 30),
  ('Foreman', 30),
  ('Gang Leader', 30)
on conflict do nothing;

insert into public.sites (code, name) values
  ('2AJ','Labour Camps Ajman'),
  ('3DP','3D Printing Laboratory'),
  ('3HW','3D Halfway House'),
  ('ADQ','Adnoc New Corp HQ'),
  ('AJB','Ajman Ruler Breakwater'),
  ('AJE','Ajman Sewerage Treatment Plant'),
  ('AP4','Ajman Sewerage Phase 4'),
  ('ASE','Ajman Sludge to Energy Plant'),
  ('AWO','Sixco Workshop Ajman'),
  ('BAA','Base Jebel Ali Carpentry'),
  ('BAB','Base Jebel Ali Rebar Shop'),
  ('BAD','Diving Activities Marine Department'),
  ('BAF','Workshop Steel Fabrication'),
  ('BFM','Besix Facilities Management'),
  ('BJE','Bahrain LNG Jetty'),
  ('BNF','Building and Facilities'),
  ('BSP','Sheet Pile Section Marine Base Ajman'),
  ('CAB','Porta Cabin'),
  ('CIV','Ivory Coast Africa'),
  ('CMS','Central Marine Support'),
  ('COE','Center of Excellence'),
  ('CST','Central Store Dubai'),
  ('DBP','Dubai Belgian Pavilion'),
  ('DCA','Dubai Water Canal Infrastructure'),
  ('DCB','Dubai Canal Business Bay'),
  ('DCR','Dubai Creek Harbour Tower Raft'),
  ('DFM','Deira Fish Market Marine Works'),
  ('DFP','Dubai French Pavilion'),
  ('DG3','Palm Deira Bridge'),
  ('DJE','Duqm Jetty Marine Project'),
  ('DPB','Dubai Pedestrian Bridges'),
  ('DR3','Contract under DRO Project'),
  ('DRO','Dubai Reverse Osmose Treatment Plant'),
  ('DS2','Shindagha Corridor Phase 2'),
  ('DSB','Dubai Shindagha Bridge'),
  ('DSP','Dammam Stadium'),
  ('DST','Dubai Deep Stormwater Tunnel'),
  ('DUT','Dubai Uptown Tower'),
  ('DWE','Dubai Waste to Energy EPC'),
  ('DWO','Dubai Waste to Energy O&M'),
  ('DWS','Dubai Waste to Energy SPC'),
  ('DXB','Sixco Main Office Dubai'),
  ('E20','Expo 2020'),
  ('ETJ','EACOP Jetty Load Out Facilities'),
  ('FDT','Fujairah Dibba Terminal'),
  ('FE3','Ferrari World Phase 2'),
  ('FPR','SBB1 Pier Repair Works'),
  ('FQ2','Fujairah Quay Wall'),
  ('GA2','Guggenheim Abu Dhabi MEP'),
  ('GAD','Guggenheim Abu Dhabi'),
  ('HO','Sixco Head Office Dubai'),
  ('HO2','Head Office Extension'),
  ('HO3','SHO3 Head Office Extension 3'),
  ('JT2','Jebel Ali Treatment Plant Extension'),
  ('JT3','Emergency Works Jebel Ali STP'),
  ('JTP','Jebel Ali Treatment Plant'),
  ('JVI','Jumeirah VIP Island'),
  ('KWO','Sixco Workshop KSA'),
  ('LCD','Sixco Labour Camps Dubai'),
  ('LCS','Sixco Labour Camps Sharjah'),
  ('LO1','LO1'),
  ('LOC','LOC'),
  ('MBA','Marine Base Ajman'),
  ('MGD','Mangrove Park Development'),
  ('MOL','Provision for Staff'),
  ('MSR','Masdar Institute Neighbourhood'),
  ('NAK','O&M Company Nakian'),
  ('OSS','SEA Code'),
  ('OWO','Sixco Workshop Oman'),
  ('OX1','OXAGON Port Dredging Stage 1'),
  ('OX3','DUBA FSRU Terminal'),
  ('POH','Pilot Ocean Harvest'),
  ('PPP','Besix Concessions'),
  ('QA3','HIA Airfield Pavement Remediation'),
  ('QA4','Hamad Airport Pavement VO07'),
  ('QA5','Concourse D and E Works'),
  ('QA6','Hamad International Airport Runway'),
  ('QAE','Qatar Ashghal Expressway'),
  ('QCS','Central Store Qatar'),
  ('QGT','QPMC Gabbro Terminal Expansion'),
  ('QHO','Qatar Head Office'),
  ('QLT','Lusail Plaza Towers'),
  ('QMO','Musaimeer Pumping Station'),
  ('QNF','North Field Expansion Onshore'),
  ('QP2','Al Mourjan Island Marine Works'),
  ('QSV','Qatar Sixco Village'),
  ('QT3','IASTW Phase IIIA Expansion'),
  ('QTP','Qatar Sewage Treatment Plant'),
  ('QW2','Wakrah Stadium Facade'),
  ('QWO','Sixco Workshop Qatar'),
  ('QWS','Al Wakrah Stadium'),
  ('RA2','Royal Atlantis Beach'),
  ('RAK','Sixco Yard Ras Al Khaimah'),
  ('RAP','Royal Atlantis Palm'),
  ('RD2','Refuse Derived Fuel O&M'),
  ('RDF','Refuse Derived Fuel'),
  ('RL3','Ras Laffan 3'),
  ('SAB','Arada Bus Stations'),
  ('SCM','Precast Department Ajman'),
  ('SEA','Sixco Marine Department Ajman'),
  ('SJP','Sohar Jetty Project'),
  ('SM2','Sharjah Mina Khalid Phase 2'),
  ('SP1','Sea Palace Beach Rectification'),
  ('SWO','Sixco Workshop Saudi'),
  ('TEC','Tech Department Dubai'),
  ('TPS','Stormwater Tunnel Terminal Pumping'),
  ('TR2','Tramway Al Safouh 2'),
  ('TR3','Pedestrian Bridge Al Safouh'),
  ('UAQ','Umm Al Quwain Quay Wall'),
  ('URM','United Ready Mix Qatar'),
  ('WAM','Al Warsan Project'),
  ('WIS','Wasl Island Shoreline'),
  ('WOR','Sixco Workshop Dubai'),
  ('YTP','Yas Theme Park'),
  ('ZN2','Zayed Museum'),
  ('ZNM','Sheikh Zayed National Museum')
on conflict (code) do nothing;
